/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "base.h"
#include "gpio.h"
#include "adc.h"
#include "tim.h"
#include "rcc.h"

#include <stdint.h>


int main(void)
{
	gpio_init();
	adc_init();
	for(;;);
}
